import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import {
  AlertTriangle,
  Filter,
  Search,
  CheckCircle2,
  XCircle,
  Clock,
  ArrowUpRight,
  Loader2,
  Shield,
  Check,
  X
} from 'lucide-react';
import { fetchAlerts, updateAlertStatus, AlertItem } from '../services/api';

export const AlertsPage: React.FC = () => {
  const queryClient = useQueryClient();
  const [riskFilter, setRiskFilter] = useState<string>('all');
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState<string>('');

  const [confirmModalAlert, setConfirmModalAlert] = useState<{ alert: AlertItem; targetStatus: string } | null>(null);

  const { data: alerts, isLoading, isError } = useQuery({
    queryKey: ['alerts', riskFilter, statusFilter],
    queryFn: () => fetchAlerts(riskFilter, statusFilter),
  });

  const statusMutation = useMutation({
    mutationFn: ({ alertId, status }: { alertId: string; status: string }) =>
      updateAlertStatus(alertId, status),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['alerts'] });
      queryClient.invalidateQueries({ queryKey: ['dashboardSummary'] });
      setConfirmModalAlert(null);
    },
  });

  const handleStatusChangeClick = (alert: AlertItem, targetStatus: string) => {
    setConfirmModalAlert({ alert, targetStatus });
  };

  const handleConfirmStatusChange = () => {
    if (confirmModalAlert) {
      statusMutation.mutate({
        alertId: confirmModalAlert.alert.id,
        status: confirmModalAlert.targetStatus,
      });
    }
  };

  const filteredAlerts = alerts?.filter((a) => {
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      return (
        a.subject_id.toLowerCase().includes(q) ||
        a.alert_code.toLowerCase().includes(q) ||
        a.title.toLowerCase().includes(q)
      );
    }
    return true;
  });

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="bg-slate-900/60 p-6 rounded-xl border border-slate-800 flex flex-col lg:flex-row lg:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold text-slate-100 flex items-center space-x-2">
            <AlertTriangle className="w-5 h-5 text-amber-400" />
            <span>Behavioral Risk Alerts Triage</span>
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Real-time alert queue generated by transparent 10-indicator rule engine anomalies and ML probability spikes.
          </p>
        </div>

        {/* Filter Controls */}
        <div className="flex flex-wrap items-center gap-3">
          <div className="relative">
            <Search className="w-4 h-4 text-slate-500 absolute left-3 top-2.5" />
            <input
              type="text"
              placeholder="Filter by address or alert code..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-9 pr-4 py-2 bg-slate-950 border border-slate-800 rounded-lg text-xs font-mono text-slate-200 focus:outline-none focus:border-cyan-500 min-w-[240px]"
            />
          </div>

          <div className="flex items-center space-x-2">
            <select
              value={riskFilter}
              onChange={(e) => setRiskFilter(e.target.value)}
              className="px-3 py-2 bg-slate-950 border border-slate-800 rounded-lg text-xs font-mono text-slate-200 focus:outline-none focus:border-cyan-500"
            >
              <option value="all">All Risks</option>
              <option value="critical">Critical Only</option>
              <option value="high">High Only</option>
              <option value="medium">Medium Only</option>
              <option value="low">Low Only</option>
            </select>

            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="px-3 py-2 bg-slate-950 border border-slate-800 rounded-lg text-xs font-mono text-slate-200 focus:outline-none focus:border-cyan-500"
            >
              <option value="all">All Statuses</option>
              <option value="new">New</option>
              <option value="under_review">Under Review</option>
              <option value="resolved">Resolved</option>
              <option value="false_positive">False Positive</option>
            </select>
          </div>
        </div>
      </div>

      {/* Alerts Feed Table */}
      <div className="bg-slate-900/60 rounded-xl border border-slate-800 overflow-hidden">
        {isLoading ? (
          <div className="p-12 text-center space-y-3">
            <Loader2 className="w-8 h-8 text-cyan-400 animate-spin mx-auto" />
            <p className="text-xs text-slate-400 font-mono">Loading Behavioral Alert Feed...</p>
          </div>
        ) : isError ? (
          <div className="p-8 text-center text-xs text-rose-400">Failed to load alerts feed.</div>
        ) : filteredAlerts?.length === 0 ? (
          <div className="p-12 text-center text-xs text-slate-400 font-mono">
            No alerts match the selected filters.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-950 border-b border-slate-800 text-slate-400 font-mono uppercase text-[10px]">
                <tr>
                  <th className="px-6 py-3">Alert Code</th>
                  <th className="px-6 py-3">Subject ID</th>
                  <th className="px-6 py-3">Risk Score</th>
                  <th className="px-6 py-3">Top Behavioral Signal</th>
                  <th className="px-6 py-3">Status</th>
                  <th className="px-6 py-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60 font-mono">
                {filteredAlerts?.map((alert) => (
                  <tr key={alert.id} className="hover:bg-slate-800/30 transition-colors">
                    <td className="px-6 py-4 font-bold text-slate-200">{alert.alert_code}</td>
                    <td className="px-6 py-4 text-cyan-400 max-w-[200px] truncate">{alert.subject_id}</td>
                    <td className="px-6 py-4">
                      <span className={`px-2 py-0.5 rounded font-bold border ${
                        alert.risk_level === 'critical' ? 'bg-purple-500/10 text-purple-400 border-purple-500/30' :
                        alert.risk_level === 'high' ? 'bg-rose-500/10 text-rose-400 border-rose-500/30' :
                        alert.risk_level === 'medium' ? 'bg-amber-500/10 text-amber-400 border-amber-500/30' :
                        'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
                      }`}>
                        {alert.risk_score} ({alert.risk_level.toUpperCase()})
                      </span>
                    </td>
                    <td className="px-6 py-4 text-slate-300 font-sans">{alert.top_signal}</td>
                    <td className="px-6 py-4">
                      <span className={`px-2.5 py-1 rounded text-[10px] uppercase font-bold border ${
                        alert.status === 'new' ? 'bg-rose-500/10 text-rose-400 border-rose-500/30' :
                        alert.status === 'under_review' ? 'bg-amber-500/10 text-amber-400 border-amber-500/30' :
                        alert.status === 'resolved' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30' :
                        'bg-slate-800 text-slate-400 border-slate-700'
                      }`}>
                        {alert.status.replace('_', ' ')}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-right space-x-2 font-sans">
                      <Link
                        to={`/investigate/${alert.subject_id}`}
                        className="px-2.5 py-1 bg-slate-800 hover:bg-slate-700 text-cyan-400 text-[11px] rounded border border-slate-700 inline-flex items-center gap-1"
                      >
                        <span>Investigate</span>
                        <ArrowUpRight className="w-3 h-3" />
                      </Link>

                      {alert.status !== 'resolved' && (
                        <button
                          onClick={() => handleStatusChangeClick(alert, 'resolved')}
                          className="px-2 py-1 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 text-[11px] rounded"
                        >
                          Resolve
                        </button>
                      )}

                      {alert.status !== 'false_positive' && (
                        <button
                          onClick={() => handleStatusChangeClick(alert, 'false_positive')}
                          className="px-2 py-1 bg-slate-800 hover:bg-slate-700 text-slate-400 border border-slate-700 text-[11px] rounded"
                        >
                          False Positive
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Confirmation Modal */}
      {confirmModalAlert && (
        <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 max-w-md w-full space-y-4 shadow-2xl">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-bold text-slate-100 uppercase tracking-wider flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-amber-400" />
                <span>Confirm Alert Status Transition</span>
              </h3>
              <button onClick={() => setConfirmModalAlert(null)} className="text-slate-400 hover:text-slate-200">
                <X className="w-4 h-4" />
              </button>
            </div>

            <p className="text-xs text-slate-300 leading-relaxed">
              Are you sure you want to mark alert <b>{confirmModalAlert.alert.alert_code}</b> for subject <b>{confirmModalAlert.alert.subject_id}</b> as <b className="uppercase text-cyan-400">{confirmModalAlert.targetStatus.replace('_', ' ')}</b>?
            </p>

            <div className="flex justify-end space-x-3 pt-2">
              <button
                onClick={() => setConfirmModalAlert(null)}
                className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold rounded-lg border border-slate-700"
              >
                Cancel
              </button>
              <button
                onClick={handleConfirmStatusChange}
                disabled={statusMutation.isPending}
                className="px-4 py-2 bg-cyan-500 hover:bg-cyan-400 text-slate-950 text-xs font-bold rounded-lg flex items-center space-x-1.5"
              >
                {statusMutation.isPending && <Loader2 className="w-3.5 h-3.5 animate-spin" />}
                <span>Confirm Status Change</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
